[package]
name = "catalyze"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.9"
prost-types = "0.9"
heck = "0.4"
anyhow = "1.0.53"
petgraph = "0.6.0"

[build-dependencies]
which = { version = "4.2" }


[workspace]
members = ["./catalyze-build", "./protoc-gen-echo"]
