[package]
name = "catalyze-prost"
version = "0.1.0"
edition = "2021"

[dependencies]
prost-types = "0.9"
heck = "0.4"
anyhow = "1.0.53"
petgraph = "0.6.0"
lazy_static = "1.4.0"
prost = "0.9"
catalyze={path = "../"}
[build-dependencies]
which = { version = "4.2" }
